sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "4.6.1"
  - "5"
  - "6"
  - "node"
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run lint
  - npm test
  - npm run build:prod
  - npm run server:prod:ci &
  - sleep 3
  - npm run e2e
